# Generated by Django 5.1.3 on 2024-11-20 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='seguidores',
            field=models.ManyToManyField(blank=True, related_name='seguindo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='afiliacoes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='especialidades',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='formacao',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
