# Generated by Django 5.1.3 on 2024-11-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_seguidores_alter_perfil_afiliacoes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='seguidores',
        ),
        migrations.AddField(
            model_name='perfil',
            name='seguindo',
            field=models.ManyToManyField(blank=True, related_name='seguidores', to='usuarios.perfil'),
        ),
    ]
